name: model_comps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - xarray
  - netcdf4
  - beautifulsoup4
  - cmocean
  - erddapy
  - cartopy
  - matplotlib
  - dask
  - pip
  - ipython
  - oceans
  - geopandas
  - bottleneck
  - lxml
  - tqdm
  - pydap
  - jupyterlab
  - copernicusmarine
  - cool_maps
